### ISSUE TITLE
Look at presentation without cloning

### ISSUE THREAD

**Issue by BoGGoG** [inokawazu/yamagata202312#1]
Hi Markus,
is there a possibility you could also put one rendered presentation here?
It's a bit cumbersome if everyone who wants to take a look at it has to first download it and install the dependencies.
Kind of defeats the original purpose of putting the presentation here?

Cool setup btw!

**Comment by inokawazu** [comment]
Thanks Marco!

Thanks for pointing this out. I have [released](https://github.com/inokawazu/yamagata202312/releases/tag/v1) the pdf version in the releases section of the repo. Look to the right of the repo screen if you are using a browser.

This version of the talk is actually for a talk I will give today at Yama U. The holotube version is [here](https://github.com/inokawazu/holotube2023) with release [here](https://github.com/inokawazu/holotube2023/releases/tag/v4).
